version: '2'
services:
  antispam:
    build: .
    environment:
      PASSWORD: 'apassword'
    volumes:
      - "filter:/var/lib/rspamd"
    ports:
      - 11334:11334
      - 11333:11333

volumes:
  filter:
    driver: local
